site_name: KNOWRON
theme:
  name: material
  language: en
  palette:
    primary: deep orange
    accent: indigo
  logo: logo.png
  favicon: icon.png
  extra:
    alternate:
      - name: English
        link: /en/
        lang: en
      - name: Deutsch
        link: /de/
        lang: de
  features:
    - navigation.indexes
    - navigation.sections
    - toc.follow
plugins:
  - search
  - glightbox
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: ⚓︎
      permalink_title: Permalink
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: "index.en.md"
  - Getting Started:
      - "Native Assistant (Mobile)": "Getting Started/quick-start-guide-assistant.md"
      - "Control Suite (Web)": "Getting Started/quick-start-guide-cs.md"
  - Control Suite Features:
      - "Features/charts.md"
      - "Features/searchhistory.md"
      - "Features/search.md"
      - "Features/tutorials.md"
      - "Features/documents.md"
      - "Features/articles.md"
      - "Features/machineinventory.md"
      - "Features/searchfeedback.md"
      - "Features/partsinventory.md"
      - "Features/adminpanel.md"
  - Native Assistant Features:
      - "Features/troubleshooting.md"
      - "Features/supportscreen.md"

  - Admin:
      - Security and Access:
          - "Admin Documentation/Security and Access/product_access_groups.md"
          - "Admin Documentation/Security and Access/roles_and_permissions.md"
          - "Admin Documentation/Security and Access/data_security_and_privacy.en.md"